arch = "X86"

[assembler]
command = "clang --target=x86_64-unknown-linux-elf -fuse-ld=lld"
instruction_step = 1

[isla]
default_memory_size = 8
page_bits = 12

[isla.symbols]
pa_base_address = 0x1000

[execution]
fuel = 1000

[registers.defaults]
rax = 0
rcx = 0
rdx = 0
rbx = 0
rsp = 0
rbp = 0
rsi = 0
rdi = 0
r8 = 0
r9 = 0
r10 = 0
r11 = 0
r12 = 0
r13 = 0
r14 = 0
r15 = 0
rflags = 0
