(env
 (dev
  (flags
   (:standard -w -20-32-33-34-39-67))))

(rocq.extraction
 (prelude ArmInstExtr)
 (theories
  Ltac2
  Stdlib
  stdpp
  SailStdpp
  Hammer
  RecordUpdate
  Equations
  SailTinyArm
  Riscv
  SailTinyX86
  ASCommon
  ArchSem
  ArchSemArm
  ArchSemRiscV
  ArchSemX86)
 (extracted_files
  ArmInst.ml
  ArmInst.mli
  SeqModel.ml
  SeqModel.mli
  Ascii.ml
  Ascii.mli
  base.ml
  base.mli
  Basics.ml
  Basics.mli
  BinInt.ml
  BinInt.mli
  ZArith_dec.ml
  ZArith_dec.mli
  CMonads.ml
  CMonads.mli
  BinNat.ml
  BinNat.mli
  BinNums.ml
  BinNums.mli
  NatDef.ml
  NatDef.mli
  BinPos.ml
  BinPos.mli
  PosDef.ml
  PosDef.mli
  CBase.ml
  CBase.mli
  CBitvector.ml
  CBitvector.mli
  CBool.ml
  CBool.mli
  CArith.ml
  CArith.mli
  CList.ml
  CList.mli
  CMaps.ml
  CMaps.mli
  COption.ml
  COption.mli
  Common.ml
  Common.mli
  CVec.ml
  CVec.mli
  countable.ml
  countable.mli
  CResult.ml
  CResult.mli
  CSets.ml
  CSets.mli
  Datatypes.ml
  Datatypes.mli
  decidable.ml
  decidable.mli
  definitions.ml
  definitions.mli
  Effects.ml
  Effects.mli
  Exec.ml
  Exec.mli
  fin0.ml
  fin0.mli
  finite.ml
  finite.mli
  fin_maps.ml
  fin_maps.mli
  Fin.ml
  Fin.mli
  FMon.ml
  FMon.mli
  gmap.ml
  gmap.mli
  HexString.ml
  HexString.mli
  Interface.ml
  Interface.mli
  list_monad.ml
  list_monad.mli
  list_relations.ml
  list_relations.mli
  ListDef.ml
  ListDef.mli
  List0.ml
  List0.mli
  list_numbers.ml
  list_numbers.mli
  listset.ml
  listset.mli
  mapset.ml
  mapset.mli
  CRelationClasses.ml
  CRelationClasses.mli
  GRel.ml
  GRel.mli
  Nat.ml
  Nat.mli
  numbers.ml
  numbers.mli
  option.ml
  option.mli
  propset.ml
  propset.mli
  RecordSet.ml
  RecordSet.mli
  pretty.ml
  pretty.mli
  sets.ml
  sets.mli
  Specif.ml
  Specif.mli
  String0.ml
  String0.mli
  strings.ml
  strings.mli
  Classes.ml
  Classes.mli
  ArchInst.ml
  ArchInst.mli
  CandidateExecutions.ml
  CandidateExecutions.mli
  Instances.ml
  Instances.mli
  Values.ml
  Values.mli
  MachineWord.ml
  MachineWord.mli
  FromSail.ml
  FromSail.mli
  ConcurrencyInterfaceV2.ml
  ConcurrencyInterfaceV2.mli
  System_types.ml
  System_types.mli
  BinNatDef.ml
  BinNatDef.mli
  PeanoNat.ml
  PeanoNat.mli
  TypeCasts.ml
  TypeCasts.mli
  Sumbool.ml
  Sumbool.mli
  ConcurrencyInterfaceBuiltinsV2.ml
  ConcurrencyInterfaceBuiltinsV2.mli
  ConcurrencyInterfaceTypesV2.ml
  ConcurrencyInterfaceTypesV2.mli
  Rdefinitions.ml
  Rdefinitions.mli
  ClassicalDedekindReals.ml
  ClassicalDedekindReals.mli
  StateT.ml
  StateT.mli
  ISAManip.ml
  ISAManip.mli
  ConstructiveCauchyReals.ml
  ConstructiveCauchyReals.mli
  QArith_base.ml
  QArith_base.mli
  Ring_theory.ml
  Ring_theory.mli
  QExtra.ml
  QExtra.mli
  Qabs.ml
  Qabs.mli
  Qreduction.ml
  Qreduction.mli
  ConstructiveCauchyRealsMult.ml
  ConstructiveCauchyRealsMult.mli
  String1.ml
  String1.mli
  System.ml
  System.mli
  BinaryString.ml
  BinaryString.mli
  Operators_mwords.ml
  Operators_mwords.mli
  GenPromising.ml
  GenPromising.mli
  TermModels.ml
  TermModels.mli
  vector0.ml
  vector0.mli
  VectorDef.ml
  VectorDef.mli
  Vector.ml
  Vector.mli
  UMPromising.ml
  UMPromising.mli
  VMPromising.ml
  VMPromising.mli
  HVec.ml
  HVec.mli
  fin_sets.ml
  fin_sets.mli
  list_basics.ml
  list_basics.mli
  Tiny_x86.ml
  Tiny_x86.mli
  Tiny_x86_types.ml
  Tiny_x86_types.mli
  X86Inst.ml
  X86Inst.mli
  OperationalX86TSO.ml
  OperationalX86TSO.mli))

(library
 (name archsem)
 (package archsem)
 (modules_without_implementation arch)
 (libraries zarith))
