(******************************************************************************)
(*                                ArchSem                                     *)
(*                                                                            *)
(*  Copyright (c) 2021                                                        *)
(*      Thibaut Pérami, University of Cambridge                               *)
(*      Yeji Han, Seoul National University                                   *)
(*      Shreeka Lohani, University of Cambridge                               *)
(*      Zongyuan Liu, Aarhus University                                       *)
(*      Nils Lauermann, University of Cambridge                               *)
(*      Jean Pichon-Pharabod, University of Cambridge, Aarhus University      *)
(*      Brian Campbell, University of Edinburgh                               *)
(*      Alasdair Armstrong, University of Cambridge                           *)
(*      Ben Simner, University of Cambridge                                   *)
(*      Peter Sewell, University of Cambridge                                 *)
(*                                                                            *)
(*  Redistribution and use in source and binary forms, with or without        *)
(*  modification, are permitted provided that the following conditions        *)
(*  are met:                                                                  *)
(*                                                                            *)
(*   1. Redistributions of source code must retain the above copyright        *)
(*      notice, this list of conditions and the following disclaimer.         *)
(*                                                                            *)
(*   2. Redistributions in binary form must reproduce the above copyright     *)
(*      notice, this list of conditions and the following disclaimer in the   *)
(*      documentation and/or other materials provided with the distribution.  *)
(*                                                                            *)
(*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       *)
(*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         *)
(*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS         *)
(*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE            *)
(*  COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,      *)
(*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,      *)
(*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS     *)
(*  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *)
(*  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR     *)
(*  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE    *)
(*  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  *)
(*                                                                            *)
(******************************************************************************)

(* Efficient reimplementation of stdpp's [Pos.reverse] using Zarith.

   Semantics: for n with bits b_{k-1} b_{k-2} ... b_1 b_0 (MSB..LSB, b_{k-1}=1),
   the result has bits 1 b_0 b_1 ... b_{k-2}: the leading 1-bit stays fixed,
   everything below it is reversed. Raises Invalid_argument on n <= 0.

   Strategy: split n into its fixed top bit (msb) and the remaining m = k-1 low
   bits (low). To reverse just those m bits we reverse a whole W-bit word and
   shift right by (W - m):

     - For m <= 64: We do the bit shuffling directly on an int64
     - For m > 64: We do the reversal byte-by-byte

   The code in this file was generated by Claude Sonnet 5 *)

(* Reverse all 64 bits of a machine word *)
let reverse64 (x : int64) : int64 =
  let open Int64 in
  let m1 = 0x5555555555555555L in
  let m2 = 0x3333333333333333L in
  let m4 = 0x0F0F0F0F0F0F0F0FL in
  let m8 = 0x00FF00FF00FF00FFL in
  let m16 = 0x0000FFFF0000FFFFL in
  let x =
    logor
      (shift_right_logical (logand x (lognot m1)) 1)
      (shift_left (logand x m1) 1)
  in
  let x =
    logor
      (shift_right_logical (logand x (lognot m2)) 2)
      (shift_left (logand x m2) 2)
  in
  let x =
    logor
      (shift_right_logical (logand x (lognot m4)) 4)
      (shift_left (logand x m4) 4)
  in
  let x =
    logor
      (shift_right_logical (logand x (lognot m8)) 8)
      (shift_left (logand x m8) 8)
  in
  let x =
    logor
      (shift_right_logical (logand x (lognot m16)) 16)
      (shift_left (logand x m16) 16)
  in
  let x = logor (shift_right_logical x 32) (shift_left x 32) in
  x

(* Reverse the 8 bits of a byte *)
let reverse_byte (b : int) : int =
  let b = ((b land 0xF0) lsr 4) lor ((b land 0x0F) lsl 4) in
  let b = ((b land 0xCC) lsr 2) lor ((b land 0x33) lsl 2) in
  let b = ((b land 0xAA) lsr 1) lor ((b land 0x55) lsl 1) in
  b

(* Conversion to and from int64, but actually unsigned *)
let z_to_int64_bits (z : Z.t) : int64 =
  if Z.testbit z 63 then Z.to_int64 (Z.sub z (Z.shift_left Z.one 64))
  else Z.to_int64 z

let z_of_int64_bits (x : int64) : Z.t =
  if Int64.compare x 0L < 0 then Z.add (Z.of_int64 x) (Z.shift_left Z.one 64)
  else Z.of_int64 x

(* Reverse the low m-bit field of [low] (0 <= low < 2^m), for m > 64. *)
let reverse_wide (low : Z.t) (m : int) : Z.t =
  let nbytes = (m + 7) / 8 in
  let s = Z.to_bits low in
  let slen = String.length s in
  let get_byte i = if i < slen then Char.code s.[i] else 0 in
  let out = Bytes.create nbytes in
  for i = 0 to nbytes - 1 do
    Bytes.set out i (Char.chr (reverse_byte (get_byte (nbytes - 1 - i))))
  done;
  let full_rev = Z.of_bits (Bytes.to_string out) in
  Z.shift_right full_rev ((nbytes * 8) - m)

let pos_reverse (n : Z.t) : Z.t =
  if Z.sign n <= 0 then invalid_arg "pos_reverse: expected a positive integer";
  let k = Z.numbits n in
  if k = 1 then n (* n = 1: nothing below the fixed top bit *)
  else begin
    let m = k - 1 in
    let msb = Z.shift_left Z.one m in
    let low = Z.sub n msb in
    let rev_low =
      if m <= 64 then
        let low64 = z_to_int64_bits low in
        let r = reverse64 low64 in
        z_of_int64_bits (Int64.shift_right_logical r (64 - m))
      else reverse_wide low m
    in
    Z.logor msb rev_low
  end
